import React from 'react';
import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/app/components/QueryProvider";
import { MoodProvider } from "./components/MoodProvider";

export const metadata: Metadata = {
  title: "Insightly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased bg-slate-100"
      >
        <MoodProvider>
          <QueryProvider>
            <div className="container mx-auto my-4">
              {children}
            </div>
          </QueryProvider>
        </MoodProvider>
      </body>
    </html>
  );
}
